### ISSUE TITLE
[DOCUMENTATION] Symbol for Net Erosion

### ISSUE THREAD

**Issue by SethCallewaert** [cn-ws/cn-ws#55]
Documentation references: https://github.com/cn-ws/cn-ws/blame/master/docs/watem-sedem.rst#L35

**B. I have a question considering this section:**

Is there a Symbol for Net Erosion rate to clearly distinguish it from annual erosion rate E?

**Comment by Sachagobeyn** [comment]
See https://github.com/cn-ws/cn-ws/issues/56, closing
