### ISSUE TITLE
[DOCUMENTATION] Tillage Erosion

### ISSUE THREAD

**Issue by SethCallewaert** [cn-ws/cn-ws#57]
Documentation references: https://github.com/cn-ws/cn-ws/blame/master/docs/watem-sedem.rst#L154

**B. I have a question considering this section:**

E_t is described as Erosion or Deposition rate, yet it is defined to be always negative? 
Once again I feel like erosion should still be defined as a positive value and it should be considered as an in and out flux to make a distinction between erosion and deposition. 
At the moment, it is not clear from this paragraph when E_t is considered Erosion or Deposition.

**Comment by Sachagobeyn** [comment]
See https://github.com/cn-ws/cn-ws/pull/140 and  https://github.com/cn-ws/cn-ws/pull/111
