### ISSUE TITLE
[DOCUMENTATION]Negative erosion

### ISSUE THREAD

**Issue by SethCallewaert** [cn-ws/cn-ws#94]
Documentation references: https://github.com/cn-ws/cn-ws/blame/5f98fea84fd4d09cac26b5cd6e5bff4428393a96/docs/output.rst#L129

**B. I have a question considering this section:**

The output given here is a negative value, so or the output value should be given positively (preferred) or it should be stated here that this value is negative.

**Comment by Sachagobeyn** [comment]
See discussion https://github.com/cn-ws/cn-ws/pull/111
