### ISSUE TITLE
[DOCUMENTATION] cumulative.rst

### ISSUE THREAD

**Issue by SethCallewaert** [cn-ws/cn-ws#96]
Documentation references: https://github.com/cn-ws/cn-ws/blame/5f98fea84fd4d09cac26b5cd6e5bff4428393a96/docs/output.rst#L189

**A. I want to add something to this section:**

a bit more information should be included on this raster output, what exactly is given here?

**Comment by daarende** [comment]
https://cn-ws.github.io/cn-ws/output.html#cumulative-rst
